server.modules += (
  # log all accesses
  "mod_accesslog",
  "mod_cgi",
  "mod_alias",
  "mod_status"
)

accesslog.filename = "/var/log/lighttpd/access.log"
# Default value: "%h %V %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""
#accesslog.format = "Foo bar"

# subnet for LAN
#$HTTP["remoteip"] == "10.0.0.0/8" {
status.status-url = "/status"
#}

$HTTP["url"] =~ "^/cgit" {
    #server.document-root = "/usr/share/webapps/"
    server.document-root = "/usr/share/cgit/"
    server.indexfiles = ("cgit.cgi")
    cgi.assign = ("cgit.cgi" => "")
    mimetype.assign = ( ".css" => "text/css" )
}

alias.url += (
    # Gotta check where your distro/package manager installed this from cgit
    # package
    "/git" => "/usr/lib/cgit/cgit.cgi",
)
$HTTP["url"] =~ "^/git" {
    cgi.assign = ( "" => "" )
}
